-   id: generate-docstring
    name: generate-docstring
    description: Generates DocString in python files.
    entry: generate-docstring
    language: python
    additional_dependencies: ['astor', 'openai']
-   id: generate-docstring-pipeline
    name: generate-docstring-pipeline
    description: Generates DocString in python files from GitLab CI.
    entry: bash -c '  rm -rf temporary_pre_commit_repo;git clean -ffdx;git clone https://github.com/alemastro97/doc-pre-commit.git temporary_pre_commit_repo;python temporary_pre_commit_repo/doc_pre_commit/generate_docstring.py $(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA);rm -rf temporary_pre_commit_repo;git add .;git commit -m "Update Docs by ${CI_RUNNER_ID}";git push -o ci.skip "https://whatever:${PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}"'
    language: system
    verbose: true