-   id: generate-docstring
    name: generate-docstring
    description: Generates DocString in python files.
    entry: generate-docstring
    language: python
    additional_dependencies: ['astor', 'openai']